import { Providers } from './Providers';
import { Footer } from './components/Footer/Footer';
import { Navbar } from './components/Navbar/Navbar'
import { Oswald } from './components/assets/Fonts';
import './globals.css'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  
  return (
    <html lang="en">
      <body className={Oswald.className}>
        <Providers>
          <Navbar/>
          {children}
          <Footer/>
        </Providers>
      </body>
    </html>
  )
}
