import { Providers } from "./Providers";
import "./globals.css";
import AppLayout from "./AppLayout";
import { CartInterface } from "./types";
import RestClient from "./RestClient/RequestTypes";
import BaseUrl from "./RestClient/ApiUrls";
import { cookies } from "next/headers";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const { data }: { data: CartInterface } = await RestClient.GetRequest(
    BaseUrl.getCart,
    cookies().get("accessToken")?.value
  );

  return (
    <html lang="en">
      <body >
        <Providers>
          <AppLayout cartData={data}>
            {children}
          </AppLayout>
        </Providers>
      </body>
    </html>
  );
}
